### ISSUE TITLE
Roundabout is getting collapsed in a bad way

### ISSUE THREAD

**Issue by dmfutcher** [a-b-street/osm2streets#105] opened 2022-10-16 14:41 UTC
I've hit a panic when trying out the "find home" feature in the 15 minute neighbourhood tool: "must_get_sidewalk broken by (Road)". This is using the Edinburgh map I mentioned in this osm2streets bug https://github.com/a-b-street/osm2streets/issues/102.

Panic is coming from https://github.com/a-b-street/abstreet/blob/master/map_model/src/objects/road.rs#L106. Doing a bit of debugging, I can see there's 2 possible sidewalks in `found`, which obviously leads to panic because `found.len() != 1`. 

I've got two workarounds I've played with. First is to add a safe version of `must_get_sidewalk` that returns an Option, and skip calculating on that node in `all_walking_costs_from` ([diff](https://github.com/a-b-street/abstreet/compare/master...dmfutcher:abstreet:safe-get_sidewalk)). The other is to change that if-condition to `found.len() == 0` and just take the 0th sidewalk in those situations ([diff](https://github.com/a-b-street/abstreet/compare/master...dmfutcher:abstreet:fix-15m-find-home-panic)). I've got zero intuition as to which is correct, but both let me play with this tool on the large Edinburgh map. Happy work an PR to fix this properly.

**Comment by dabreegster** [comment] 2022-11-04 15:34
Root cause is `Transformation::CollapseSausageLinks` incorrectly collapsing this

**Comment by dabreegster** [comment] 2022-11-25 15:19
This is actually even more subtle than I thought. Notice in the screenshots, that road to the north (https://www.openstreetmap.org/way/320244260) is missing. It happens to get clipped out of the Edinburgh boundary. So the roundabout actually _does_ look like a sausage link there. But in the osm2streets tool, it's hard to arrange the viewport to clip it out.

Regardless, `CollapseSausageLinks` shouldn't touch `junction=roundabout` I guess. We're now discarding OSM tags during transformations, so we'd have to think about the right way to plumb this data through.

Punting on this for now.

**Comment by dabreegster** [comment] 2022-12-16 13:56
This now appears fixed after recent improvements in clipping logic. A/B Street pulls in those changes, so I'll close this. If we hit anything similar in the future, can revisit

**Comment by dabreegster** [comment] 2023-01-28 19:29
Found a new case at https://www.openstreetmap.org/way/235499756:
![Screenshot from 2023-01-28 19-27-53](https://user-images.githubusercontent.com/1664407/215287201-f19f1274-429d-428c-92de-bf30fcdd7b75.png)
![Screenshot from 2023-01-28 19-27-44](https://user-images.githubusercontent.com/1664407/215287202-eae5ed6d-3d10-4a2f-91cf-fed1373b6eb6.png)
Will add a test here and figure this out

**Closed** 2023-01-31 10:33 UTC
