### ISSUE TITLE
Way to share current view?

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/osm2streets#75] opened 2022-08-18 05:55 UTC
I'm just looking at this:

![image](https://user-images.githubusercontent.com/1825120/185304567-5375e76a-b62c-4edc-8ca2-ba5633f769a5.png)

Would be neat if there were a 'Share URL' button.

**Comment by dabreegster** [comment] 2022-08-18 07:30
Duplicate of #31

**Closed by dabreegster** 2022-08-18 07:30 UTC
