### ISSUE TITLE
Collapsing a road breaks

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/osm2streets#202] opened 2023-02-17 15:21 UTC
https://a-b-street.github.io/osm2streets/#20.28/51.47795/-2.52882

https://user-images.githubusercontent.com/1664407/219694301-ce73d775-ac9c-456f-8e68-31ec6b170145.mp4

Not really sure what's going wrong here yet, but the final result having no intersection geometry is causing downstream problems in the LTN tool. Fixing the root cause would be great.

**Comment by BudgieInWA** [comment] 2023-02-18 03:02
Something that might be relevant about this crash: after the collapse, there is a road that joins the intersection at both ends! I wonder if that is the cause for all these crashes.

The small intersection (with "S" underneath it) is merged with the large "tion Way" intersection, and that tiny sliver of road at the top also connects both. After the merge, that tiny sliver is no longer trimmed, and reveals it's full length.

**Closed** 2023-02-23 14:09 UTC
Labels: bug
