### ISSUE TITLE
Lanes for bus and bicycles not shown up

### ISSUE THREAD

**Issue by robhubi** [a-b-street/osm2streets#230] opened 2024-01-18 22:37 UTC
**Real situation:**
![grafik](https://github.com/a-b-street/osm2streets/assets/38103976/19b8d4b2-1aa6-4d2a-95c6-f3483293f358)

Tags of [Way 194755333](https://www.openstreetmap.org/way/194755333) :
```
lanes	4
lanes:forward	3
lanes:backward	1
	
cycleway:right	share_busway
cycleway:right:lane	advisory
cycleway:left	lane
cycleway:left:lane	advisory
	
turn:lanes:forward	left|through;right||
	
vehicle:lanes:forward	yes|yes|no|no
bus:lanes:forward	yes|yes|designated|designated
bicycle:lanes:forward	yes|yes|yes|designated
	
vehicle:lanes:backward	yes|yes
bicycle:lanes:backward	yes|designated
	
sidewalk:both	separate
foot	use_sidepath
	
highway	primary
lit	yes
maxspeed	50
name	Sankt-Peter-Hauptstraße
oneway	no
ref	B67a
smoothness	excellent
surface	asphalt
```
**A/B Street (V0.3.49)**
Turn arrows missing, no bus lane, no cycle lane on the right
![grafik](https://github.com/a-b-street/osm2streets/assets/38103976/e17c8ffc-af8d-4911-9362-5c2465c4083e)

**Comment by ginnyTheCat** [comment] 2024-03-17 13:40
This is fixed on the osm2streets side as far as I can tell.
![imagen](https://github.com/a-b-street/osm2streets/assets/35173023/f0537f4f-f627-48e9-9685-f02b0b07ec93)
I currently can't compile a/b street, but that seems to be caused by the osm2lanes module being moved out of osm2streets, causing the imports to fail or something similar.

**Comment by dabreegster** [comment] 2024-03-17 13:55
I'm not planning to update A/B Street anytime soon; any development and validation should be happening here for now. Thanks for fixing this with Muv!

**Closed by dabreegster** 2024-03-17 13:55 UTC
